version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.3
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pyarrow
    versions:
    - 2.0.0
